# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 연락처
    url: /contact/
    weight: 10
  - name: 챌린지
    url: /challenge/
    weight: 20
  - name: 소개
    url: /about/
    weight: 30
  - name: 프로젝트
    url: /project/
    weight: 40
  - name: 여행
    url: /travel/
    weight: 50
